name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY_BASE64 }}
        key_format: base64
        script: |
          cd ~/bolokobul
          git pull origin main
          rm -f tmp/pids/server.pid
          nohup bash -c 'RAILS_ENV=production rails server -b 0.0.0.0' > log.txt 2>&1 &